import { describe, it, expect } from "vitest";
import request from "supertest";
import app from "../../app.js";
import { Category } from "../../modules/categories/category.model.js";
import {
  seedAdminAuth,
  seedAdminUser,
  signTokenFor,
  seedCategory,
} from "../helpers/fixtures.js";

describe("GET /api/v1/categories", () => {
  it("returns the list of categories to anonymous visitors", async () => {
    await seedCategory({ name: "Protein" });
    await seedCategory({ name: "Vitamins" });

    const res = await request(app).get("/api/v1/categories");
    expect(res.status).toBe(200);
    expect(res.body.data.length).toBeGreaterThanOrEqual(2);
  });
});

describe("POST /api/v1/categories", () => {
  it("creates a category when called with admin auth", async () => {
    const { authHeader } = await seedAdminAuth();

    const res = await request(app)
      .post("/api/v1/categories")
      .set(authHeader)
      .send({ name: "Wellness", description: "Supplements for daily wellness." });

    expect(res.status).toBe(201);
    expect(res.body.data.name).toBe("Wellness");
    // Slug is auto-generated by the service.
    expect(res.body.data.slug).toMatch(/wellness/);
  });

  it("rejects unauthenticated calls with 401", async () => {
    const res = await request(app)
      .post("/api/v1/categories")
      .send({ name: "Anon Category" });
    expect(res.status).toBe(401);
  });

  it("rejects customer-role calls with 403", async () => {
    const user = await seedAdminUser({
      role: "User",
      email: "cat-user@stylogist.test",
      phone: "03001110001",
    });
    const token = signTokenFor(user);

    const res = await request(app)
      .post("/api/v1/categories")
      .set("Authorization", `Bearer ${token}`)
      .send({ name: "Should Not Save" });

    expect(res.status).toBe(403);
  });

  it("rejects payloads missing the required name", async () => {
    const { authHeader } = await seedAdminAuth();
    const res = await request(app)
      .post("/api/v1/categories")
      .set(authHeader)
      .send({ description: "no name" });
    expect(res.status).toBe(400);
  });
});

describe("PATCH /api/v1/categories/:id", () => {
  it("updates the category name and regenerates the slug if name changed", async () => {
    const { authHeader } = await seedAdminAuth();
    const cat = await seedCategory({ name: "Old Name" });

    const res = await request(app)
      .patch(`/api/v1/categories/${cat._id}`)
      .set(authHeader)
      .send({ name: "Renamed Category" });

    expect(res.status).toBe(200);
    expect(res.body.data.name).toBe("Renamed Category");
  });
});

describe("DELETE /api/v1/categories/:id", () => {
  it("removes the category", async () => {
    const { authHeader } = await seedAdminAuth();
    const cat = await seedCategory({ name: "Deletable" });

    const res = await request(app)
      .delete(`/api/v1/categories/${cat._id}`)
      .set(authHeader);

    expect(res.status).toBe(200);
    const after = await Category.findById(cat._id);
    expect(after).toBeNull();
  });
});
